spring:
  application:
    name: camel-json-router

camel:
  servlet:
    mapping:
      contextPath: /*

logging:
  level:
    root: INFO

api2api:
  endpoint:
    a: http://localhost:9090/external/a
    b: http://localhost:9090/external/b
